database:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "secret"
  dbname: "godfather"
  sslmode: "disable"
auth:
  jwtKey: "secret"
s3_cloud:
  url: "https://storage.yandexcloud.net/"
  region: "ru-central1"
  bucket: "godfather"
server:
  host: "localhost"
